# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/tongyuang/study/UWGIX/Course/TECHIN 509/Practice/Week-5/tic-tac-toe/NameInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QDialog(object):
    def setupUi(self, QDialog):
        QDialog.setObjectName("QDialog")
        QDialog.resize(300, 87)
        QDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.textEdit = QtWidgets.QTextEdit(QDialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 40, 260, 30))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(QDialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 171, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(QDialog)
        self.pushButton.setGeometry(QtCore.QRect(200, 10, 81, 26))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(QDialog)
        QtCore.QMetaObject.connectSlotsByName(QDialog)

    def retranslateUi(self, QDialog):
        _translate = QtCore.QCoreApplication.translate
        QDialog.setWindowTitle(_translate("QDialog", "Please input your name"))
        self.label.setText(_translate("QDialog", "Please Input your Name:"))
        self.pushButton.setText(_translate("QDialog", "ok"))
